#!/usr/bin/env python3
"""Vendor axi.py into a tool repo, with a test that fails if the copy is edited.

    python3 vendor.py <tool-repo-root> <package>

writes two files into the tool repo:

    <package>/axi.py              a two-line header, then this repo's axi.py byte for byte
    tests/test_axi_vendored.py    fails if the body no longer matches the header's hash

Tools do not call this directly: their `make vendor-axi` clones this repo at a pinned
tag and runs it. It refuses to run from anything but a clean checkout of the tag that
matches axi.py's __version__, because the header it writes claims exactly that. Pass
--dev to vendor a work-in-progress copy for a local try; the generated test rejects a
-dev header, so that copy cannot pass the tool's CI.
"""
import argparse
import hashlib
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
SOURCE = HERE / "axi.py"
UPSTREAM = "craig-ai-tooling/axi-py"

TEST_TEMPLATE = '''\
"""Generated by craig-ai-tooling/axi-py vendor.py. Do not edit; rerun `make vendor-axi`.

@PKG@/axi.py is a vendored copy of the output and exit-code contract every Python AXI
shares. An edit made here is how the tools drift apart, so this test fails on one.
Change it upstream in craig-ai-tooling/axi-py, tag it, then run
`make vendor-axi AXI_PY_REF=<tag>` in this repo.
"""
import hashlib
import pathlib
import re
import unittest

AXI = pathlib.Path(__file__).resolve().parent.parent / "@PKG@" / "axi.py"
HEADER = re.compile(rb"# VENDORED from craig-ai-tooling/axi-py (v[0-9]+\\.[0-9]+\\.[0-9]+) sha256=([0-9a-f]{64})\\n")


class VendoredAxiIsUnedited(unittest.TestCase):
    def setUp(self):
        self.raw = AXI.read_bytes()
        self.header = HEADER.match(self.raw)
        self.assertIsNotNone(self.header, f"{AXI} has no release header; run `make vendor-axi`")

    def test_body_matches_the_hash_in_its_header(self):
        body = self.raw.split(b"\\n", 2)[2]
        self.assertEqual(
            hashlib.sha256(body).hexdigest(), self.header.group(2).decode(),
            f"{AXI} was edited in place. Revert it, make the change in craig-ai-tooling/axi-py, "
            "tag it, then `make vendor-axi AXI_PY_REF=<tag>`.")

    def test_header_names_the_version_the_body_declares(self):
        version = re.search(rb'^__version__ = "([^"]+)"$', self.raw, re.M)
        self.assertIsNotNone(version, f"{AXI} declares no __version__")
        self.assertEqual(b"v" + version.group(1), self.header.group(1))


if __name__ == "__main__":
    unittest.main()
'''


def version(source=SOURCE):
    m = re.search(r'^__version__ = "([^"]+)"$', source.read_text(encoding="utf-8"), re.M)
    if not m:
        raise SystemExit(f"error: {source} declares no __version__")
    return m.group(1)


def render_module(body, ref):
    digest = hashlib.sha256(body).hexdigest()
    head = (f"# VENDORED from {UPSTREAM} {ref} sha256={digest}\n"
            f"# Do not edit here: change {UPSTREAM}, tag it, then run `make vendor-axi AXI_PY_REF=<tag>`.\n")
    return head.encode() + body


def render_test(package):
    return TEST_TEMPLATE.replace("@PKG@", package)


def vendor(root, package, ref, source=SOURCE):
    """Write both files. Returns the paths written."""
    root = pathlib.Path(root)
    pkg_dir = root / package
    if not (pkg_dir / "__init__.py").is_file():
        raise SystemExit(f"error: {pkg_dir} is not a package (no __init__.py)")
    mod = pkg_dir / "axi.py"
    test = root / "tests" / "test_axi_vendored.py"
    test.parent.mkdir(exist_ok=True)
    mod.write_bytes(render_module(source.read_bytes(), ref))
    test.write_text(render_test(package), encoding="utf-8")
    return mod, test


def checkout_ref(repo=HERE):
    """The tag HEAD sits on exactly, or None when HEAD is untagged or axi.py is dirty."""
    def git(*args):
        return subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True)
    tag = git("describe", "--tags", "--exact-match", "HEAD")
    if tag.returncode != 0:
        return None
    if git("status", "--porcelain", "--", "axi.py").stdout.strip():
        return None
    return tag.stdout.strip()


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("root", help="the tool repo's root directory")
    p.add_argument("package", help="the tool's package directory, e.g. opp_axi")
    p.add_argument("--dev", action="store_true",
                   help="vendor an untagged copy; the generated test fails it on purpose")
    a = p.parse_args(argv)
    want = f"v{version()}"
    if a.dev:
        ref = f"{want}-dev"
    else:
        ref = checkout_ref()
        if ref != want:
            print(f"error: refusing to vendor: axi.py says {want} but this checkout is at "
                  f"{ref or 'no exact tag, or axi.py is modified'}. "
                  f"Run it from a clean clone of tag {want}, or pass --dev for a local try.",
                  file=sys.stderr)
            return 1
    for path in vendor(a.root, a.package, ref):
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
